export class StationData {
    stationData() {
        return [
            { name: 'Acton Town', zone: '3' },
            { name: 'Aldgate', zone: '1' },
            { name: 'Aldgate East', zone: '1' },
            { name: 'Alperton', zone: '4' },
            { name: 'Amersham', zone: '6d' },
            { name: 'Angel', zone: '1' },
            { name: 'Archway', zone: '2' },
            { name: 'Arnos Grove', zone: '4' },
            { name: 'Arsenal', zone: '2' },
            { name: 'Baker Street', zone: '1' },
            { name: 'Balham', zone: '3' },
            { name: 'Bank', zone: '1' },
            { name: 'Barbican', zone: '1' },
            { name: 'Barking', zone: '4' },
            { name: 'Barkingside', zone: '5' },
            { name: 'Barons Court', zone: '2' },
            { name: 'Bayswater', zone: '1' },
            { name: 'Becontree', zone: '5' },
            { name: 'Belsize Park', zone: '2' },
            { name: 'Bermondsey', zone: '2' },
            { name: 'Bethnal Green', zone: '2' },
            { name: 'Blackfriars', zone: '1' },
            { name: 'Blackhorse Road', zone: '3' },
            { name: 'Bond Street', zone: '1' },
            { name: 'Borough', zone: '1' },
            { name: 'Boston Manor', zone: '4' },
            { name: 'Bounds Green', zone: '3' },
            { name: 'Bow Road', zone: '2' },
            { name: 'Brent Cross', zone: '3' },
            { name: 'Brixton', zone: '2' },
            { name: 'Buckhurst Hill', zone: '5' },
            { name: 'Burnt Oak', zone: '4' },
            { name: 'Caledonian Road', zone: '2' },
            { name: 'Camden Town', zone: '2' },
            { name: 'Canada Water', zone: '2' },
            { name: 'Canary Wharf', zone: '2' },
            { name: 'Canning Town', zone: '3' },
            { name: 'Cannon Street', zone: '1' },
            { name: 'Canons Park', zone: '5' },
            { name: 'Chalfont & Latimer', zone: '6c' },
            { name: 'Chalk Farm', zone: '2' },
            { name: 'Chancery Lane', zone: '1' },
            { name: 'Charing Cross', zone: '1' },
            { name: 'Chesham', zone: '6d' },
            { name: 'Chigwell', zone: '5' },
            { name: 'Chiswick Park', zone: '3' },
            { name: 'Chorleywood', zone: '6b' },
            { name: 'Clapham Common', zone: '2' },
            { name: 'Clapham North', zone: '2' },
            { name: 'Clapham South', zone: '2' },
            { name: 'Cockfosters', zone: '5' },
            { name: 'Colindale', zone: '4' },
            { name: 'Colliers Wood', zone: '3' },
            { name: 'Covent Garden', zone: '1' },
            { name: 'Croxley', zone: '6a' },
            { name: 'Dagenham East', zone: '5' },
            { name: 'Dagenham Heathway', zone: '5' },
            { name: 'Debden', zone: '6' },
            { name: 'Dollis Hill', zone: '3' },
            { name: 'Ealing Broadway', zone: '3' },
            { name: 'Ealing Common', zone: '3' },
            { name: 'Earl\'s Court', zone: '1+2' },
            { name: 'East Acton', zone: '2' },
            { name: 'East Finchley', zone: '3' },
            { name: 'East Ham', zone: '3' },
            { name: 'East Putney', zone: '2+3' },
            { name: 'Eastcote', zone: '5' },
            { name: 'Edgware', zone: '5' },
            { name: 'Elephant & Castle', zone: '1+2' },
            { name: 'Elm Park', zone: '6' },
            { name: 'Embankment', zone: '1' },
            { name: 'Epping', zone: '6' },
            { name: 'Euston', zone: '1' },
            { name: 'Euston Square', zone: '1' },
            { name: 'Fairlop', zone: '5' },
            { name: 'Farringdon', zone: '1' },
            { name: 'Finchley Central', zone: '4' },
            { name: 'Finchley Road', zone: '2' },
            { name: 'Finsbury Park', zone: '2' },
            { name: 'Fulham Broadway', zone: '2' },
            { name: 'Gants Hill', zone: '4' },
            { name: 'Gloucester Road', zone: '1' },
            { name: 'Golders Green', zone: '3' },
            { name: 'Goldhawk Road', zone: '2' },
            { name: 'Goodge Street', zone: '1' },
            { name: 'Grange Hill', zone: '5' },
            { name: 'Great Portland Street', zone: '1' },
            { name: 'Green Park', zone: '1' },
            { name: 'Greenford', zone: '4' },
            { name: 'Hainault', zone: '5' },
            { name: 'Hampstead', zone: '2' },
            { name: 'Hanger Lane', zone: '3' },
            { name: 'Hatton Cross', zone: '5' },
            { name: 'Heathrow Terminal 4', zone: '6' },
            { name: 'Hendon Central', zone: '3' },
            { name: 'High Barnet', zone: '5' },
            { name: 'High Street Kensington', zone: '1' },
            { name: 'Highbury & Islington', zone: '2' },
            { name: 'Highgate', zone: '3' },
            { name: 'Hillingdon', zone: '6' },
            { name: 'Holborn', zone: '1' },
            { name: 'Holland Park', zone: '2' },
            { name: 'Holloway Road', zone: '2' },
            { name: 'Hornchurch', zone: '6' },
            { name: 'Hounslow Central', zone: '4' },
            { name: 'Hounslow East', zone: '4' },
            { name: 'Hounslow West', zone: '5' },
            { name: 'Hyde Park Corner', zone: '1' },
            { name: 'Ickenham', zone: '6' },
            { name: 'Kennington', zone: '2' },
            { name: 'Kentish Town', zone: '2' },
            { name: 'Kilburn', zone: '2' },
            { name: 'Kilburn Park', zone: '2' },
            { name: 'Kingsbury', zone: '4' },
            { name: 'Knightsbridge', zone: '1' },
            { name: 'Ladbroke Grove', zone: '2' },
            { name: 'Lambeth North', zone: '1' },
            { name: 'Lancaster Gate', zone: '1' },
            { name: 'Latimer Road', zone: '2' },
            { name: 'Leicester Square', zone: '1' },
            { name: 'Leyton', zone: '3' },
            { name: 'Leytonstone', zone: '3' },
            { name: 'Liverpool Street', zone: '1' },
            { name: 'London Bridge', zone: '1' },
            { name: 'Loughton', zone: '6' },
            { name: 'Maida Vale', zone: '2' },
            { name: 'Manor House', zone: '2' },
            { name: 'Mansion House', zone: '1' },
            { name: 'Marble Arch', zone: '1' },
            { name: 'Marylebone', zone: '1' },
            { name: 'Mile End', zone: '2' },
            { name: 'Mill Hill East', zone: '4' },
            { name: 'Monument', zone: '1' },
            { name: 'Moor Park', zone: '6+6a' },
            { name: 'Moorgate', zone: '1' },
            { name: 'Morden', zone: '4' },
            { name: 'Mornington Crescent', zone: '2' },
            { name: 'Neasden', zone: '3' },
            { name: 'Newbury Park', zone: '4' },
            { name: 'North Acton', zone: '2' },
            { name: 'North Ealing', zone: '3' },
            { name: 'North Greenwich', zone: '2' },
            { name: 'North Harrow', zone: '5' },
            { name: 'Northfields', zone: '3' },
            { name: 'Northolt', zone: '5' },
            { name: 'Northwick Park', zone: '4' },
            { name: 'Northwood', zone: '6' },
            { name: 'Northwood Hills', zone: '6' },
            { name: 'Notting Hill Gate', zone: '1' },
            { name: 'Oakwood', zone: '5' },
            { name: 'Old Street', zone: '1' },
            { name: 'Osterley', zone: '4' },
            { name: 'Oval', zone: '2' },
            { name: 'Oxford Circus', zone: '1' },
            { name: 'Paddington', zone: '1' },
            { name: 'Park Royal', zone: '3' },
            { name: 'Parsons Green', zone: '2' },
            { name: 'Perivale', zone: '4' },
            { name: 'Piccadilly Circus', zone: '1' },
            { name: 'Pimlico', zone: '1' },
            { name: 'Pinner', zone: '5' },
            { name: 'Plaistow', zone: '3' },
            { name: 'Preston Road', zone: '4' },
            { name: 'Putney Bridge', zone: '2' },
            { name: 'Queensbury', zone: '4' },
            { name: 'Queensway', zone: '1' },
            { name: 'Ravenscourt Park', zone: '2' },
            { name: 'Rayners Lane', zone: '5' },
            { name: 'Redbridge', zone: '4' },
            { name: 'Regent\'s Park', zone: '1' },
            { name: 'Rickmansworth', zone: '6a' },
            { name: 'Roding Valley', zone: '5' },
            { name: 'Rotherhithe', zone: '2' },
            { name: 'Royal Oak', zone: '2' },
            { name: 'Ruislip', zone: '6' },
            { name: 'Ruislip Gardens', zone: '5' },
            { name: 'Ruislip Manor', zone: '6' },
            { name: 'Russell Square', zone: '1' },
            { name: 'Seven Sisters', zone: '3' },
            { name: 'Shadwell', zone: '2' },
            { name: 'Sloane Square', zone: '1' },
            { name: 'Snaresbrook', zone: '4' },
            { name: 'South Ealing', zone: '3' },
            { name: 'South Harrow', zone: '5' },
            { name: 'South Kensington', zone: '1' },
            { name: 'South Ruislip', zone: '5' },
            { name: 'South Wimbledon', zone: '3' },
            { name: 'South Woodford', zone: '4' },
            { name: 'Southfields', zone: '3' },
            { name: 'Southgate', zone: '4' },
            { name: 'Southwark', zone: '1' },
            { name: 'Stamford Brook', zone: '2' },
            { name: 'Stanmore', zone: '5' },
            { name: 'Stepney Green', zone: '2' },
            { name: 'Stockwell', zone: '2' },
            { name: 'Stratford', zone: '3' },
            { name: 'Sudbury Hill', zone: '4' },
            { name: 'Sudbury Town', zone: '4' },
            { name: 'Surrey Quays', zone: '2' },
            { name: 'Swiss Cottage', zone: '2' }];

    }

}
